apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: jenkins
data:
  JENKINS_OPTS: "--prefix=/jenkins"
  JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

  # Example of custom jenkins.xml configuration
  jenkins.xml: |
    <?xml version='1.1' encoding='UTF-8'?>
    <jenkins>
      <numExecutors>2</numExecutors>
      <mode>EXCLUSIVE</mode>
      <useSecurity>true</useSecurity>
      <authorizationStrategy class="hudson.security.AuthorizationStrategy$Unsecured"/>
      <securityRealm class="hudson.security.SecurityRealm$None"/>
      <slaveAgentPort>-1</slaveAgentPort>
      <disableRememberMe>true</disableRememberMe>
      <label/>
      <mode>EXCLUSIVE</mode>
      <workspaceDir>${ITEM_ROOTDIR}/workspace</workspaceDir>
      <buildsDir>${ITEM_ROOTDIR}/builds</buildsDir>
      <projectNamingStrategy class="jenkins.model.ProjectNamingStrategy$DefaultProjectNamingStrategy"/>
      <quietPeriod>5</quietPeriod>
      <scmCheckoutRetryCount>0</scmCheckoutRetryCount>
      <viewsTabBar class="hudson.views.DefaultViewsTabBar"/>
      <myViewsTabBar class="hudson.views.DefaultMyViewsTabBar"/>
      <primaryView>All</primaryView>
      <mode>NORMAL</mode>
      <numExecutors>2</numExecutors>
      <mode>EXCLUSIVE</mode>
    </jenkins>
