apiVersion: v1
kind: ResourceQuota
metadata:
  name: jenkins-resource-quota
  namespace: jenkins
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    persistentvolumeclaims: "5"
    pods: "10"
    services: "5"
    services.nodeports: "5"
