apiVersion: v1
kind: ResourceQuota
metadata:
  name: testhello-resource-quota
  namespace: hello
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "20"
    services: "10"
    persistentvolumeclaims: "10"
    configmaps: "20"
    secrets: "20"
    replicationcontrollers: "10"
    resourcequotas: "1"
    services.loadbalancers: "5"
    services.nodeports: "5"
