apiVersion: v1
kind: ConfigMap
metadata:
  name: testhello-config
  namespace: hello
data:
  application.properties: |
    server.port=8080
    spring.datasource.url=jdbc:mysql://localhost:3306/testdb
    spring.datasource.username=root
    spring.datasource.password=secret
