apiVersion: v1
kind: ResourceQuota
metadata:
  name: tomcat-resource-quota
  namespace: tomcat
spec:
  hard:
    requests.cpu: "500m"           # Maximum total CPU requests for the namespace
    requests.memory: "1Gi"         # Maximum total memory requests for the namespace
    limits.cpu: "1"                # Maximum total CPU limits for the namespace
    limits.memory: "2Gi"           # Maximum total memory limits for the namespace
    pods: "10"                     # Maximum number of pods that can be created in the namespace
    services: "5"                  # Maximum number of services that can be created in the namespace
    persistentvolumeclaims: "5"    # Maximum number of PersistentVolumeClaims
    configmaps: "10"               # Maximum number of ConfigMaps
    secrets: "10"                  # Maximum number of Secrets
