apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-config
  namespace: tomcat
data:
  server.xml: |
    <Server port="8005" shutdown="SHUTDOWN">
      <Service name="Catalina">
        <Connector port="8080" protocol="HTTP/1.1"
                   connectionTimeout="20000"
                   redirectPort="8443" />
        <Engine name="Catalina" defaultHost="localhost">
          <Host name="localhost"  appBase="webapps"
                unpackWARs="true" autoDeploy="true">
            <Valve className="org.apache.catalina.valves.AccessLogValve"
                   directory="logs" prefix="localhost_access_log"
                   suffix=".txt" pattern="%h %l %u %t &quot;%r&quot; %s %b" />
          </Host>
        </Engine>
      </Service>
    </Server>
  logging.properties: |
    handlers = 1catalina.org.apache.juli.FileHandler, java.util.logging.ConsoleHandler
    .level = INFO
    java.util.logging.ConsoleHandler.level = FINE
